eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

spring:
  data :
    mongodb :
      username : root
      password : root
      host : localhost
      port : 27017
      database : customer

server:
  port: 8090
