eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

spring:
  data :
    mongodb :
      username : samet
      password : samet
      host : localhost
      port : 27017
      database : customer
      authentication-database : admin
server:
  port: 8090
